export enum ActionTypes {
  UPDATE_COLOR = 'UPDATE_COLOR',
  UPDATE_CELLS = 'UPDATE_CELLS',
  UPDATE_TOOL_LAYER_CELLS = 'UPDATE_TOOL_LAYER_CELLS',
  UPDATE_BRUSH_SIZE = 'UPDATE_BRUSH_SIZE',
  UPDATE_ZOOM = 'UPDATE_ZOOM',
  MOVE_MOUSE = 'MOVE_MOUSE',
  SAVE_HISTORY = 'SAVE_HISTORY',
  SET_TOOL = 'SET_TOOL',
  UNDO = 'UNDO',
  REDO = 'REDO',
  CLEAR = 'CLEAR',
}
