export enum ActionTypes {
  SET_COLOR = 'SET_COLOR',
  UPDATE_CELL = 'UPDATE_CELL',
  MOVE_MOUSE = 'MOVE_MOUSE',
  SAVE_HISTORY = 'SAVE_HISTORY',
  SET_TOOL = 'SET_TOOL',
  UNDO = 'UNDO',
  REDO = 'REDO',
}
